# Generated by Django 5.0.7 on 2024-07-14 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_item_color_alter_item_image_alter_item_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=3, validators=[django.core.validators.RegexValidator(code='invalid_size', message='Only alphabetical characters are allowed.', regex='^[A-Za-z]+$')]),
        ),
    ]
