# Generated by Django 5.0.7 on 2024-07-14 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_item_material_alter_item_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=3, null=True, validators=[django.core.validators.RegexValidator(code='invalid_size', message='Only alphabetical characters are allowed.', regex='^[A-Za-z]+$')]),
        ),
    ]
