# Generated by Django 5.0.7 on 2024-07-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_item_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                    ("XXL", "Double Extra Large"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
