# Generated by Django 4.2.14 on 2024-07-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_item_author_item_book_category_alter_item_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description_short',
            field=models.CharField(max_length=500),
        ),
    ]
