# Generated by Django 5.0.7 on 2024-07-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_item_color_item_author_item_book_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
