# Generated by Django 5.0.7 on 2024-07-16 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_item_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
    ]
