# Generated by Django 5.0.7 on 2024-07-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_item_description_short'),
        ('core', '0018_item_color_item_size'),
    ]

    operations = [
    ]
